# main: main.cpp greetings_prototype_1.cpp # This version will give a linker error.
# 	g++ -Wall -std=c++17 main.cpp greetings_prototype_1.cpp -o main

main: main.cpp greetings_prototype_2.cpp
	g++ -Wall -std=c++17 main.cpp greetings_prototype_2.cpp -o main

clean:
	del main.exe